fix a spir-val error in the cooperative_matrix_constant_null test (#3568)
Fixes a validation error reported by recent versions of spirv-val:

```
error: line 13: OpTypeCooperativeMatrixKHR Scope is limited to Workgroup and Subgroup
  %8 = OpTypeCooperativeMatrixKHR %uint %3 %uint_12 %uint_12 %3
```

Basically, the cooperative matrix scope needs to be 2 (Workgroup) or 3
(Subgroup) instead of the current 0 (CrossDevice).

Since 3 (Subgroup) is the most common usage, for now at least, I've gone
with it.